In [1]:
import argparse
import os
import matplotlib.pyplot as plt
from matplotlib.pyplot import imshow
import scipy.io
import scipy.misc
import numpy as np
import pandas as pd
import PIL
from PIL import ImageFont, ImageDraw, Image
import tensorflow as tf
import tensorflow.keras
from tensorflow.python.framework.ops import EagerTensor

from tensorflow.keras.models import load_model
# from yad2k.models.keras_yolo import yolo_head
# from yad2k.utils.utils import draw_boxes, get_colors_for_classes
# from yad2k.utils.utils import scale_boxes, scale_boxes, read_classes
# from yad2k.utils.utils import read_anchors, preprocess_image

In [2]:
# Implement yolo filter boxes
# 1)Compute box scores by doing the element twise product (pxc_i)
# 2) Foe each box find the index xof the class with the maximum box score

In [56]:
def yolo_filter_boxes(box_confidence, box_class_probs, threshold = 0.6):
    # gives you the class scores for each box
    box_scores = box_confidence * box_class_probs
    
    # gives you the index with the highest score
    box_classes = tf.math.argmax(box_scores, axis=-1)
    
    #box_class_score = tf.math.reduce_max(box_scores, axis=-1).numpy()
    box_class_score = np.array([box_scores[i, :][box_classes.numpy()[i]] for i in range(len(box_classes.numpy()))])
    
    # filtering mask
    
    
    return box_scores, box_classes, box_class_score

In [57]:
a = np.array([
    [1],
    [2],
    [3],
    [4],
    [5]
])
b = np.array([
    [1,2,3],
    [0,1,3],
    [2,1,3],
    [9,2,1],
    [7,4,2],
])
print('Shape of a: ', a.shape)
print('Shape of b: ', b.shape)

Shape of a:  (5, 1)
Shape of b:  (5, 3)


In [58]:
b_scores, b_classes, b_class_sc = yolo_filter_boxes(a, b)

In [59]:
b_scores

array([[ 1,  2,  3],
       [ 0,  2,  6],
       [ 6,  3,  9],
       [36,  8,  4],
       [35, 20, 10]])

In [66]:
b_class_sc.reshape(5,1)

array([[ 3],
       [ 6],
       [ 9],
       [36],
       [35]])

In [82]:
def mask_func(data):
    out = np.zeros(data.shape)
    for i, x in enumerate(data):
        if x < 20:
            out[i] = True 
        else:
            out[i] = False
    return out

In [87]:
def mask_fun(data):
    out = list()
    for i, x in enumerate(data):
        if x < 20:
            out.append(True) 
        else:
            out.append(False)
    return out

In [88]:
mask_fun(b_class_sc)

[True, True, True, False, False]

In [89]:
mask_fun(b_classes)

[True, True, True, True, True]

In [ ]:
mask_fun()

In [ ]:
# implement iou


In [97]:
tf.boolean_mask([0.9, 0.3, 0.4, 0.5, 0.1], np.array([True, False, False, True, False]))

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.9, 0.5], dtype=float32)>

In [104]:
mask = np.array([True, True])

In [105]:
mask.shape

(2,)

In [106]:
tensor = [0,1,2,3]
mask = np.array([True, False, True, False])
tf.boolean_mask(tensor, mask)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2])>

In [109]:
#Create a filtering mask based on "box_class_scores" by using "threshold". The mask should have the
# same dimension as box_class_scores, and be True for the boxes you want to keep (with probability >= threshold)
mask = np.zeros(np.array(f).shape)

In [111]:
mask.shape

(5,)