In [5]:
import argparse
import os
import matplotlib.pyplot as plt
from matplotlib.pyplot import imshow
import scipy.io
import scipy.misc
import numpy as np
import pandas as pd
import PIL
from PIL import ImageFont, ImageDraw, Image
import tensorflow as tf
import tensorflow.keras
from tensorflow.python.framework.ops import EagerTensor

from tensorflow.keras.models import load_model
# from yad2k.models.keras_yolo import yolo_head
# from yad2k.utils.utils import draw_boxes, get_colors_for_classes
# from yad2k.utils.utils import scale_boxes, scale_boxes, read_classes
# from yad2k.utils.utils import read_anchors, preprocess_image

In [6]:
# Implement yolo filter boxes
# 1)Compute box scores by doing the element twise product (pxc_i)
# 2) Foe each box find the index xof the class with the maximum box score

In [82]:
def yolo_filter_boxes(box_confidence, box_class_probs, threshold = 0.6):
    box_scores = box_confidence * box_class_probs
    box_classes = tf.math.argmax(box_scores, axis=-1)
    box_class = tf.math.reduce_max(box_scores)
    box_scores_max = [c[i, :][d_arr[i]] for i in range(len(box_classes.numpy()))]
    return box_scores, box_classes, box_class, box_scores_max

In [83]:
a = np.array([
    [1],
    [2],
    [3],
    [4],
    [5]
])
b = np.array([
    [1,2,3],
    [0,1,3],
    [2,1,3],
    [9,2,1],
    [7,4,2],
])
print('Shape of a: ', a.shape)
print('Shape of b: ', b.shape)

Shape of a:  (5, 1)
Shape of b:  (5, 3)


In [85]:
c, d , e, f= yolo_filter_boxes(a, b)

In [86]:
print(c)
print(c.shape)


[[ 1  2  3]
 [ 0  2  6]
 [ 6  3  9]
 [36  8  4]
 [35 20 10]]
(5, 3)


In [87]:
(d)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 2, 2, 0, 0], dtype=int64)>

In [88]:
print(e)
print(e.shape)

tf.Tensor(36, shape=(), dtype=int32)
()


In [89]:
e.numpy()

36

In [90]:
d_arr = d.numpy()

In [91]:
d_arr

array([2, 2, 2, 0, 0], dtype=int64)

In [92]:
c[d_arr[0], :]

array([6, 3, 9])

In [93]:
d_arr[0]

2

In [81]:
c[1, :][d_arr[1]]

6

In [94]:
f

[3, 6, 9, 36, 35]

In [97]:
tf.boolean_mask([0.9, 0.3, 0.4, 0.5, 0.1], np.array([True, False, False, True, False]))

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.9, 0.5], dtype=float32)>

In [104]:
mask = np.array([True, True])

In [105]:
mask.shape

(2,)

In [106]:
tensor = [0,1,2,3]
mask = np.array([True, False, True, False])
tf.boolean_mask(tensor, mask)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2])>

In [109]:
#Create a filtering mask based on "box_class_scores" by using "threshold". The mask should have the
# same dimension as box_class_scores, and be True for the boxes you want to keep (with probability >= threshold)
mask = np.zeros(np.array(f).shape)

In [111]:
mask.shape

(5,)